# Workflow name
name: Android CI

on: 
  push: 
    branches: [master]
  pull_request:
    branches: [master]
    
    
# Where it will run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Build with Gradle
        working-directory: ./AndroidApp
        run: ./gradlew build
      - name: Run Unit Tests
        working-directory: ./AndroidApp
        run: ./gradlew test
      - name: Run connected test
        working-directory: ./AndroidApp
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Pixel 4
          script: ./gradlew connectedCheck --stacktrace
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app
          path: AndroidApp/app/build/outputs/apk/debug/app-debug.apk
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        
